### ISSUE TITLE
SpringBoot Nacos 动态刷新错误使用 SpringCloud Nacos 类

### ISSUE THREAD

**Issue by lbx-aike** [opengoofy/hippo4j#1002]
###  报错日志
```
Caused by: java.lang.ClassNotFoundException: com.alibaba.cloud.nacos.NacosConfigProperties
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 25 common frames omitted
```
###  hippo4j使用版本
 hippo4j-config-1.4.3 版本
hippo4j 使用版本
```
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.5.RELEASE</version>
            <optional>true</optional>
        </dependency>
```
### 项目环境
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.0.RELEASE</version>
        <relativePath/>
    </parent>
    <dependency>
        <groupId>com.alibaba.boot</groupId>
        <artifactId>nacos-config-spring-boot-starter</artifactId>
        <version>0.2.1</version>
    </dependency>
```
### 源码问题位置
![image](https://user-images.githubusercontent.com/20965566/202988351-7804124e-0894-45ff-bc9f-2221abae33b6.png)
### 问题
因为我们没有引入spring cloud，所以使用spring boot引入nacos使用hippo4j config会报错，@NacosInjected这个注解就会把nacos的configService注入，为什么还要用构造方法使用spring cloud nacos的类注入，我把这几行代码删除之后，打包到私服，然后在项目里使用也没有问题，所以这里构造方法注入是为了解决什么问题？

**Comment by magestacks** [comment]
已确认为问题，可以使用 1.4.1 版本或者等待 1.4.3 修复版本
