### ISSUE TITLE
[Bug] Does not conform to RFC 7230 and has been ignored

### ISSUE THREAD

**Issue by niejian** [opengoofy/hippo4j#1033]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?
hippo4j server
### 你使用了哪个版本？
1.5.0-SNAPSHOT
### 问题重现步骤
轮训，ClientWorker#checkUpdateTpIds
![image](https://user-images.githubusercontent.com/7080323/206667355-fbb58c6e-38f5-4424-8b23-6fb158c31a37.png)
返回400

**Comment by pirme** [comment]
什么场景下会出现这种问题呢

**Comment by niejian** [comment]
> 什么场景下会出现这种问题呢
我用的alibaba dubbo，server模式。客户端启动后就会提示

**Comment by niejian** [comment]
**客户端提示400**
![image](https://user-images.githubusercontent.com/7080323/206669842-e5213881-0030-4371-8eb5-0795893fe714.png)
**服务端 **
```java
java.lang.IllegalArgumentException: The HTTP header line [client-version0x0d] does not conform to RFC 7230 and has been ignored.
	at org.apache.coyote.http11.Http11InputBuffer.skipLine(Http11InputBuffer.java:1020) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:872) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:594) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:283) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```

**Comment by niejian** [comment]
加上我提的哪个pr就没问题
1.4.3 不报错

**Comment by pirme** [comment]
如果 1.4.3 可以的话，我觉得咱们应该找下具体的原因，而不是以堆积的方式去修复遗留问题。你觉得呢

**Comment by niejian** [comment]
> 如果 1.4.3 可以的话，我觉得咱们应该找下具体的原因，而不是以堆积的方式去修复遗留问题。你觉得呢

* 1.4.3没问题是因为问题：https://github.com/opengoofy/hippo4j/issues/966
* 我这边客户端使用的springboot版本是`2.3.12.RELEASE`，server端版本是2.3.2..REALEASE；如果不加在server端堆配置的话，那就得要求客户端去主动适配服务端版本，这样是不是会有局限性？

**Comment by pirme** [comment]
不好意思，我没明白本 Issue 和 https://github.com/opengoofy/hippo4j/issues/966 有什么关系？

**Comment by niejian** [comment]
> 不好意思，我没明白本 Issue 和 #966 有什么关系？

因为 https://github.com/opengoofy/hippo4j/issues/966 的问题， 所以就不会有轮训这回事了；而本issue就是因为轮训发送http 请求发生的错误
