### ISSUE TITLE
[Bug] Hippo4j monitoring error.

### ISSUE THREAD

**Issue by lbx-aike** [opengoofy/hippo4j#1387]
我们的项目使用的spring-boot框架，但是部署方式使用war方式部署
使用的是依赖配置中心模式，配置中心用的nacos，spring-boot版本2.1.3.RELEASE，jdk版本1.8，tomcat版本8.5
以下是报错信息
```
NacosValueAnnotationBeanPostProcessor_class com.alibaba.nacos.spring.context.annotation.config.NacosValueAnnotationBeanPostProcessor was destroying!
AnnotationNacosInjectedBeanPostProcessor_class com.alibaba.nacos.spring.beans.factory.annotation.AnnotationNacosInjectedBeanPostProcessor was destroying!
ConditionEvaluationReportLoggingListener_

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR]_LoggingFailureAnalysisReporter_

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method notifyConfigBuilder in cn.hippo4j.config.springboot.starter.config.DynamicThreadPoolAutoConfiguration required a bean of type 'cn.hippo4j.adapter.web.WebThreadPoolService' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
        - Bean method 'jettyWebThreadPoolHandler' in 'WebThreadPoolHandlerConfiguration.EmbeddedJetty' not loaded because @ConditionalOnClass did not find required classes 'org.eclipse.jetty.server.Server', 'org.eclipse.jetty.util.Loader', 'org.eclipse.jetty.webapp.WebAppContext'
        - Bean method 'tomcatWebThreadPoolHandler' in 'WebThreadPoolHandlerConfiguration.EmbeddedTomcat' not loaded because @ConditionalOnClass did not find required class 'org.apache.coyote.UpgradeProtocol'
        - Bean method 'undertowWebThreadPoolHandler' in 'WebThreadPoolHandlerConfiguration.EmbeddedUndertow' not loaded because @ConditionalOnClass did not find required classes 'io.undertow.Undertow', 'org.xnio.SslClientAuthMode'


Action:

Consider revisiting the entries above or defining a bean of type 'cn.hippo4j.adapter.web.WebThreadPoolService' in your configuration.

11-Jul-2023 13:51:59.857 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultThreadPoolCheckAlarmHandler' defined in class path resource [cn/hippo4j/config/springboot/starter/config/DynamicThreadPoolAutoConfiguration.class]: Unsatisfied dependency expressed through method 'defaultThreadPoolCheckAlarmHandler' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hippo4jSendMessageService' defined in class path resource [cn/hippo4j/message/config/MessageConfiguration.class]: Unsatisfied dependency expressed through method 'hippo4jSendMessageService' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notifyConfigBuilder' defined in class path resource [cn/hippo4j/config/springboot/starter/config/DynamicThreadPoolAutoConfiguration.class]: Unsatisfied dependency expressed through method 'notifyConfigBuilder' parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'cn.hippo4j.adapter.web.WebThreadPoolService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
        ... 32 more
```
所以想问怎么去关掉这个容器监控

**Comment by magestacks** [comment]
你尝试把这个包排除

```xml
<dependency>
    <groupId>cn.hippo4j</groupId>
    <artifactId>hippo4j-threadpool-spring-boot-starter-adapter-web</artifactId>
</dependency>
```
