### ISSUE TITLE
Docker 安装后，登录后台报错：Table 'hippo4j_manager.user' doesn't exist  ?

### ISSUE THREAD

**Issue by lhsaq2009** [opengoofy/hippo4j#1508]
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Environment

Mac

### Hippo4j version

develop

### What happened

Docker 安装后，登录后台报错：Table 'hippo4j_manager.user' doesn't exist 

### How to reproduce

Docker 安装后，登录后台报错：Table 'hippo4j_manager.user' doesn't exist 

### Debug logs

2023-11-03 19:11:12.571 ERROR Attempt authentication errororg.springframework.security.authentication.InternalAuthenticationServiceException:
### Cause: java.sql.SQLSyntaxErrorException: Table 'hippo4j_manager.user' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'hippo4j_manager.user' doesn't exist
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:123)
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:144)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199)
	at cn.hippo4j.auth.filter.JWTAuthenticationFilter.attemptAuthentication(JWTAuthenticationFilter.java:73)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProx

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by magestacks** [comment]
Is the database initialized?

**Comment by lhsaq2009** [comment]
> Is the database initialized?

我仅仅只是创建了 hippo4j_manager 这个 schema。

我以为项目启动后，会自动创建数据表。
难道需要我额外的触发，或 自己去数据库执行数据表的初始化创建吗？

文档里就是这样写的，

```SQL
docker run -d -p 6691:6691 --name hippo4j-server \
-e DATASOURCE_MODE=mysql \
-e DATASOURCE_HOST=xxx.xxx.xxx.xxx \
-e DATASOURCE_PORT=3306 \
-e DATASOURCE_DB=hippo4j_manager \
-e DATASOURCE_USERNAME=root \
-e DATASOURCE_PASSWORD=root \
hippo4j/hippo4j-server
```

然后访问 Server 控制台，路径 http://localhost:6691/index.html ，默认用户名密码：admin / 123456

**Comment by magestacks** [comment]
Using the MySQL database requires initialization.
