### ISSUE TITLE
管理页面创建线程池信息不填写队列容量保存会报空指针异常

### ISSUE THREAD

**Issue by linlinjie** [opengoofy/hippo4j#273]
## Bug Report

在开始报告错误之前，请确保认真查看了以下步骤：

### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?
Hippo-4j Server

### 原因分析（如果可以）
java.lang.NullPointerException: null
    at cn.hippo4j.config.service.biz.impl.ConfigServiceImpl.getQueueCapacityByType(ConfigServiceImpl.java:217)
    at cn.hippo4j.config.service.biz.impl.ConfigServiceImpl.insertOrUpdate(ConfigServiceImpl.java:132)
    at cn.hippo4j.config.service.biz.impl.ConfigServiceImpl$$FastClassBySpringCGLIB$$64bb9278.invoke(<generated>)
### 问题重现步骤
管理后台页面-JDK线程池-线程池管理-添加
不填写队列容量-保存

**Comment by dmego** [comment]
please assign it to me.

**Comment by mabaiwan** [comment]
@dmego 欢迎 👏👏 前端项目请在这里修改 https://github.com/opengoofy/hippo4j-console

**Comment by dmego** [comment]
@mabaiwan 我看最新的代码小马哥已经把这块修改了🤣，这个 issues 应该可以关了。我先熟悉熟悉代码吧，后续有 issues 我再认领😬

**Comment by mabaiwan** [comment]
@dmego 不好意思老铁，这个应该是我在优化线程池创建 issue #380  的时候直接修改了。后面有其它 issue 再沟通哈。

**Comment by mabaiwan** [comment]
@dmego 可以看下这个 issue #252 ，有兴趣的话回复认领即可。
