### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by luojiasheng** [opengoofy/hippo4j#834]
spring-boot版本

```xml
<version>2.4.2</version>
```

引用jar
```xml
<dependency>
    <groupId>cn.hippo4j</groupId>
    <artifactId>hippo4j-config-spring-boot-starter</artifactId>
    <version>1.4.1</version>
</dependency>
```

启动报错

```java
[ ERROR] [main] [2022-10-24 14:13:45.136]-[TID: N/A] org.springframework.boot.SpringApplication -Application run failed
java.lang.IllegalStateException: Failed to introspect Class [cn.hippo4j.config.springboot.starter.refresher.event.AbstractRefreshListener] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:737)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:702)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:687)
	at org.apache.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.findFieldAnnotationMetadata(AbstractAnnotationBeanPostProcessor.java:168)
	at org.apache.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.buildAnnotatedMetadata(AbstractAnnotationBeanPostProcessor.java:242)
	at org.apache.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.findInjectionMetadata(AbstractAnnotationBeanPostProcessor.java:261)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.postProcessBeanFactory(ReferenceAnnotationBeanPostProcessor.java:153)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:299)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:178)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at com.bananain.wm.ServiceApplication.main(ServiceApplication.java:23)
Caused by: java.lang.NoClassDefFoundError: Lcn/hippo4j/common/model/WebIpAndPortInfo;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:732)
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: cn.hippo4j.common.model.WebIpAndPortInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 common frames omitted
[ INFO ] [main] [2022-10-24 14:13:45.137]-[TID: N/A] org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor -class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
[ WARN ] [Thread-8] [2022-10-24 14:13:45.139]-[TID: N/A] com.alibaba.nacos.common.notify.NotifyCenter -[NotifyCenter] Start destroying Publisher
[ WARN ] [Thread-3] [2022-10-24 14:13:45.139]-[TID: N/A] com.alibaba.nacos.common.http.HttpClientBeanHolder -[HttpClientBeanHolder] Start destroying common HttpClient
[ WARN ] [Thread-8] [2022-10-24 14:13:45.139]-[TID: N/A] com.alibaba.nacos.common.notify.NotifyCenter -[NotifyCenter] Destruction of the end
[ WARN ] [Thread-3] [2022-10-24 14:13:45.141]-[TID: N/A] com.alibaba.nacos.common.http.HttpClientBeanHolder -[HttpClientBeanHolder] Destruction of the end

Process finished with exit code 1
```

**Comment by pizihao** [comment]
启动之前先编译一下common试一下 @luojiasheng

**Comment by pizihao** [comment]
可以把hippo4j提升到1.4.2版本试一下吗，WebIpAndPortInfo是在1.4.2版本新加的 @luojiasheng

**Comment by pizihao** [comment]
或者查看一下其他的依赖，比如hippo4j-common 是否存在不同的依赖版本

**Comment by pirme** [comment]
能不能直接从中央仓库下载 1.4.2 版本，我用 2.4.2 的 springboot 启动没问题

**Comment by luojiasheng** [comment]
> 或者查看一下其他的依赖，比如hippo4j-common 是否存在不同的依赖版本

查看了版本依赖，是有hippo4j-adapter-base 1.30，hippo4j-common 1.3.0的其他引入，排除后启动没有问题了。

**Comment by luojiasheng** [comment]
> 或者查看一下其他的依赖，比如hippo4j-common 是否存在不同的依赖版本

另外，发现1.41，1.4.2 版本，hippo4j-adapter-base的版本号有1.3.0，是否保持一下好点 @pizihao 
![image](https://user-images.githubusercontent.com/40587520/197483928-9b6fa20e-2c16-4d41-9910-35299d372bb8.png)

**Comment by luojiasheng** [comment]
剔除低版本hippo4j-common，即可解决

**Comment by pirme** [comment]
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/77398366/197486301-439bfbbc-95a7-4574-a32d-9a243be511d1.png">

hippo4j 版本是统一管理的，我从中央仓库下载了 1.4.1 版本没有发现其它版本问题。是不是有其它操作导致的？

**Comment by luojiasheng** [comment]
> <img alt="image" width="1310" src="https://user-images.githubusercontent.com/77398366/197486301-439bfbbc-95a7-4574-a32d-9a243be511d1.png">
> 
> hippo4j 版本是统一管理的，我从中央仓库下载了 1.4.1 版本没有发现其它版本问题。是不是有其它操作导致的？

![image](https://user-images.githubusercontent.com/40587520/197491885-30d124f2-b85a-4239-9226-285fcf2ac630.png)
我是用的阿里仓库，有可能hippo4j-config-spring-boot-starter这个地方没有指定version导致

我这边本地hippo4j-config-spring-boot-starter整个依赖都删除了，重新导入还是有1.3.0的包出现
@pirme 你可以在idea这个地方看下有没有1.3.0的版本存在
![image](https://user-images.githubusercontent.com/40587520/197494371-834c3866-6d1b-4f3b-921b-166eea2fb534.png)
