### ISSUE TITLE
查看线程池信息报错

### ISSUE THREAD

**Issue by Skqing** [opengoofy/hippo4j#910]
## BUG 报告

在开始报告错误之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/opengoofy/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/docs/user_docs/other/issue)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？hippo4j config 还是 hippo4j server?

 hippo4j server

### 你使用了哪个版本？

docker hippo4j-server:1.4.2

<dependency>
    <groupId>cn.hippo4j</groupId>
    <artifactId>hippo4j-spring-boot-starter</artifactId>
    <version>1.4.2</version>
</dependency>

实际依赖

![image](https://user-images.githubusercontent.com/1713001/200100313-d09d5787-73c8-4d77-8a00-95abf68bd5fa.png)

### 预期行为

点击可以查看线程信息

### 实际行为

![image](https://user-images.githubusercontent.com/1713001/200100188-593814a6-4ca2-47db-96cc-eba681758d55.png)

对应异常信息
```
java.lang.NoClassDefFoundError: Could not initialize class cn.hippo4j.common.toolkit.BeanUtil
        at cn.hippo4j.core.executor.state.ThreadPoolRunStateHandler.supplement(ThreadPoolRunStateHandler.java:79) ~[hippo4j-core-1.4.2.jar!/:1.4.2]
        at cn.hippo4j.core.executor.state.AbstractThreadPoolRuntime.getPoolRunState(AbstractThreadPoolRuntime.java:110) ~[hippo4j-core-1.4.2.jar!/:1.4.2]
        at cn.hippo4j.core.executor.state.AbstractThreadPoolRuntime.getPoolRunState(AbstractThreadPoolRuntime.java:54) ~[hippo4j-core-1.4.2.jar!/:1.4.2]
        at cn.hippo4j.springboot.starter.controller.WebThreadPoolRunStateController.getPoolRunState(WebThreadPoolRunStateController.java:48) ~[hippo4j-spring-boot-starter-1.4.2.jar!/:1.4.2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.12.RELEASE.jar!/:5.2.12.RELEASE]

```

**Comment by magegoofy** [comment]
NoClassDefFoundError 应该不属于正常情况，可以看下对应源码是否存在

**Comment by Skqing** [comment]
![image](https://user-images.githubusercontent.com/1713001/200100621-c5c5c0f2-20d5-4467-affd-d1170923f98b.png)
源码能在项目里搜到

**Comment by Skqing** [comment]
![image](https://user-images.githubusercontent.com/1713001/200100649-a5a675a3-bcef-4a1e-8929-1649d79ed518.png)

**Comment by magegoofy** [comment]
我这里按照 1.4.2 复现不出来问题，检查下自己的 maven 仓库吧

**Comment by Skqing** [comment]
跟仓库应该没关系吧，我打包的jar里解压出来都有这个工具类
![image](https://user-images.githubusercontent.com/1713001/200101017-6897f11b-c8a9-4380-a30d-1f5eeeb571cb.png)
有点奇怪

**Comment by Skqing** [comment]
解决了，需要单独再加一下这个依赖
![image](https://user-images.githubusercontent.com/1713001/200102347-3fc8f914-3123-4b08-bf54-f69d31d7e2f7.png)

**Comment by magegoofy** [comment]
假的吧，hippo4j-spring-boot-starter 内部就包含 hippo4j-common
